### ISSUE TITLE
[Bug]: TypeError: `this.clients.driver.getStations(...).forEach` is not a function

### ISSUE THREAD

**Issue by syphernl** [bropat/eufy-security-ws#165]
### Version

1.2.0

### Node version

19.3.0

### Operating System type

Linux

### Operating system version

Alpine 3.17

### Describe the bug

After soon as Home Assistant connects to the websocket it crashes with:

```
2022-12-16 16:37:32.316  DEBUG [ClientsController.addSocket] New client with ip: xxx.xxx.xxx.xxx port: 47464
/opt/eufy-security-ws/node_modules/eufy-security-ws/dist/lib/forward.js:101
        this.clients.driver.getStations().forEach(station => {
                                          ^

TypeError: this.clients.driver.getStations(...).forEach is not a function
    at EventForwarder.start (/opt/eufy-security-ws/node_modules/eufy-security-ws/dist/lib/forward.js:101:43)
    at ClientsController.addSocket (/opt/eufy-security-ws/node_modules/eufy-security-ws/dist/lib/server.js:221:33)
    at WebSocketServer.<anonymous> (/opt/eufy-security-ws/node_modules/eufy-security-ws/dist/lib/server.js:302:75)
    at WebSocketServer.emit (node:events:513:28)
    at WebSocketServer.completeUpgrade (/opt/eufy-security-ws/node_modules/ws/lib/websocket-server.js:431:5)
    at WebSocketServer.handleUpgrade (/opt/eufy-security-ws/node_modules/ws/lib/websocket-server.js:339:10)
    at Server.upgrade (/opt/eufy-security-ws/node_modules/ws/lib/websocket-server.js:114:16)
    at Server.emit (node:events:513:28)
    at onParserExecuteCommon (node:_http_server:873:14)
    at onParserExecute (node:_http_server:786:3)
```

This happens after upgrading 1.1.0 to 1.2.0. Version [1.1.0](https://github.com/bropat/eufy-security-ws/releases/tag/1.1.0) still works fine. 

### To reproduce

1. Start ws
2. Install [eufy_security integration](https://github.com/fuatakgun/eufy_security) into Home Assistant
3. Connect to Home Assistant
4. Let it connect (or force a reconnect by reloading the integration)
